### PR TITLE
Notebook

### PR DESCRIPTION
**Pull request by tinchodias**
Note0: It requires https://github.com/plantec/OnBloc/pull/2
Note1: It has an issue with "selected" state of the page. It wasn't like that last week, not sure how I broke it but it could be some conflict with button hovering / press.
Note2: "Page title" may be renamed to Page tab to be more clear... or other name?
Note3: I will add more behavior.

### CODE REVIEW

**Comment by tinchodias** [comment]
Thank you! 
I didn't check well, but the themes should be on toplo instead of onbloc, shouldn't it?

**Comment by plantec** [comment]
yes. Themes have to be at Toplo level. For now, with Pierre we are trying to re-design them to manage skin and theme changes

**Comment by tinchodias** [comment]
I added close button, and the page object is closer to be a model object, observable by the notebook.

**Comment by tinchodias** [comment]
@plantec In UIs prepared for many tabs, sometimes the notebook header (the top element where the tabs are horizontally placed) is a horizontal list that can be scrolled. E.g. VSCode, I'm sure you get what I'm talking about. My question is: Do you think we should use a ToList widget with something like "beHorizontal"? or the behavior changes too much and it deserves to be anothe rwidget?

Cheers.

**Comment by tinchodias** [comment]
Or a ToListInfiniteElement, I don't know; an opinion would be welcome!

**Comment by plantec** [comment]
A simple solution is to add a button on the right opening a list of additional tabs.
One can also use an horizontal FlowLayout.
As an example, Safari do not care about that :)
But Yes, an horizontal ToListInfiniteElement could be used (I've not tested it as horizontal but normally, it should work).

**Comment by tinchodias** [comment]
Thanks Alain. The two options to support many pages are valid too. I didn't implement it.

**Pull request merged**
